import type { CSSProperties } from "react";
import theme from "../theme";

type StylesType = Record<string, CSSProperties>;

const useStyles = ({
  themeName,
  isSmallScreen,
}: {
  themeName: "light" | "dark";
  isSmallScreen: boolean;
}): StylesType => {
  return {
    //-----------------------------------------------Main
    mainContainer: {
      width: "100vw",
      height: "100vh",
      boxSizing: "border-box",
      backgroundColor: theme[themeName].background,
    },
    backgroundImg: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      position: "absolute",
      top: 0,
      left: 0,
      zIndex: 1,
    },
    mainInnerContainer: {
      width: "100%",
      height: "100%",
      zIndex: 5,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
    },
    mainInnerBodyContainer: {
      width: "100%",
      height: "100%",
      overflowY: "scroll",
      zIndex: 5,
    },
    //-----------------------------------------------Header
    headerMainContainer: {
      width: "100%",
      height: isSmallScreen ? 60 : 70,
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme[themeName].headerBack,
      paddingLeft: "5%",
      paddingRight: "5%",
      boxSizing: "border-box",
      zIndex: 10,
      boxShadow: theme[themeName].headerShadow,
    },
    headerTitle: {
      color: theme[themeName].headerText,
      fontSize: isSmallScreen ? 28 : 32,
      fontWeight: "bold",
      fontFamily: theme[themeName].font_saira,
    },
    headerIconContainer: {
      display: "flex",
      gap: 10,
    },
    headerMenuIconContainer: {
      height: theme[themeName].headerIconSize,
      width: theme[themeName].headerIconSize,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    headerMenuIcon: {
      color: theme[themeName].headerIcon,
    },
    //-----------------------------------------------Modal Menu
    modalMainContainer: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      backgroundColor: theme[themeName].menuModalBack,
      display: "flex",
      justifyContent: "flex-end",
      zIndex: 1000,
    },
    menuContainer: {
      width: 250,
      height: "100%",
      backgroundColor: theme[themeName].headerBack,
      padding: 20,
      display: "flex",
      flexDirection: "column",
      gap: 16,
    },
    menuElement: {
      padding: isSmallScreen ? 5 : 10,
      cursor: "pointer",
      fontSize: isSmallScreen ? 12 : 16,
      fontFamily: theme[themeName].font_poppins,
      color: theme[themeName].headerText,
      borderBottom: `1px solid ${theme[themeName].menuBorder}`,
      justifyContent: "space-between",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
    },

    //-----------------------------------------------Section
    //------------------------------Transparent
    sectionContainerTransparent: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      paddingLeft: "5%",
      paddingRight: "5%",
      boxSizing: "border-box",
      paddingTop: "5%",
      paddingBottom: "7%",
      backgroundColor: theme[themeName].sectionBackgroundTransparent,
      borderBottom: theme[themeName].sectionBorderTransparent,
    },
    sectionTitleTransparent: {
      width: "100%",
      fontSize: isSmallScreen ? 28 : 32,
      fontWeight: "bold",
      color: theme[themeName].sectionHeaderTransparent,
      fontFamily: theme[themeName].font_saira,
      borderBottom: `2px solid ${theme[themeName].sectionHeaderBorderTransparent}`,
      textTransform: "capitalize",
      marginBottom: 20,
    },
    sectionBodyTransparent: {
      width: "100%",
      paddingTop: 10,
      paddingBottom: 10,
    },
    //------------------------------Solid
    sectionContainerSolid: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      paddingLeft: "5%",
      paddingRight: "5%",
      boxSizing: "border-box",
      paddingTop: "5%",
      paddingBottom: "7%",
      backgroundColor: theme[themeName].sectionBackgroundSolid,
      borderBottomWidth: theme[themeName].sectionBorderSolid,
    },
    sectionTitleSolid: {
      width: "100%",
      fontSize: isSmallScreen ? 28 : 32,
      fontWeight: "bold",
      color: theme[themeName].sectionHeaderSolid,
      fontFamily: theme[themeName].font_saira,
      borderBottom: `2px solid ${theme[themeName].sectionHeaderBorderSolid}`,
      textTransform: "capitalize",
      marginBottom: 20,
    },
    sectionBodySolid: {
      width: "100%",
      paddingTop: 10,
      paddingBottom: 10,
    },
    //-----------------------------------------------Common
    //-----------------------------------------------Introduction
    introMainContainer: {
      flex: 1,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    introLeftContainer: {
      width: "50%",
      justifyContent: "center",
      alignItems: "center",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      position: "relative",
      borderRadius: 20,
    },
    introImg: {
      width: "85%",
      height: "85%",
      objectFit: "cover",
    },
    introImgOverlay: {
      width: "100%",
      height: "30%",
      background: theme[themeName].introImgOverlay,
      position: "absolute",
      bottom: 0,
      zIndex: -1,
    },
    introRightContainer: {
      width: "50%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      height: "100%",
      paddingLeft: "5%",
      boxSizing: "border-box",
    },
    introSubtitle: {
      textTransform: "capitalize",
      color: theme[themeName].introSubtitle,
      fontSize: "clamp(16px, 2vw, 24px)",
      fontFamily: theme[themeName].font_poppins,
    },
    introTitle: {
      textTransform: "capitalize",
      color: theme[themeName].introTitle,
      fontFamily: theme[themeName].font_saira,
      fontWeight: "bold",
      fontSize: "clamp(32px, 4vw, 72px)",
    },
    introDesc: {
      textTransform: "capitalize",
      color: theme[themeName].introDesc,
      fontSize: "clamp(16px, 2vw, 24px)",
      fontFamily: theme[themeName].font_poppins,
      marginBottom: 10,
    },
    introActionContainer: {
      width: "100%",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 20,
    },
    introActionButton: {
      height: theme[themeName].introButtonSize,
      width: theme[themeName].introButtonSize,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      border: `2px solid ${theme[themeName].introButton}`,
      borderRadius: 5,
    },
    introActionIcon: {
      color: theme[themeName].introButton,
    },
    //----------------------------------------------------
    sectionPoppinsBoldTextTransparent: {
      color: theme[themeName].sectionPoppinsBoldTextTransparent,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? 12 : 16,
      fontWeight: "bold",
      marginTop: isSmallScreen ? 5 : 10,
    },
    sectionPoppinsRegularTextTransparent: {
      color: theme[themeName].sectionPoppinsRegularTextTransparent,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? 12 : 16,
    },
    sectionPoppinsBoldTextSolid: {
      color: theme[themeName].sectionPoppinsBoldTextSolid,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? 12 : 16,
      fontWeight: "bold",
      marginTop: isSmallScreen ? 5 : 10,
      width: "100%",
    },
    sectionPoppinsRegularTextSolid: {
      color: theme[themeName].sectionPoppinsRegularTextSolid,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? 12 : 16,
      width: "100%",
    },

    aboutDesc: {
      width: "100%",
      paddingTop: 10,
      paddingBottom: 10,
      fontSize: isSmallScreen ? 12 : 16,
      color: theme[themeName].aboutText,
      fontFamily: theme[themeName].font_poppins,
      textTransform: "capitalize",
    },
    qualificationText: {
      width: "100%",
      paddingTop: 10,
      paddingBottom: 10,
      fontSize: isSmallScreen ? 12 : 16,
      color: theme[themeName].aboutText,
      fontFamily: theme[themeName].font_poppins,
      textTransform: "capitalize",
    },
    serviceCard: {
      padding: "5px 20px",
      borderRadius: 5,
      backgroundColor: theme[themeName].serviceCard,
      boxSizing: "border-box",
      boxShadow: `${isSmallScreen ? 5 : "7px"} ${isSmallScreen ? 5 : "7px"} ${isSmallScreen ? 5 : "7px"} ${theme[themeName].serviceCard}80`,
      color: theme[themeName].serviceCardText,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? 12 : 16,
    },
    projectContainer: {
      width: "100%",
      overflowX: "scroll",
      display: "flex",
      flexDirection: "row",
      gap: 20,
      padding: "20px 0px",
      boxSizing: "border-box",
    },
    projectCard: {
      width: 400,
      height: 510,
      flexShrink: 0,
      background: theme[themeName].projectCard,
      borderRadius: 10,
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      boxShadow: `isSmallScreen ? 5 : "7px" isSmallScreen ? 5 : "7px" isSmallScreen ? 5 : "7px" ${theme[themeName].projectCard}33`,
      position: "relative",
      flexDirection: "column",
      overflow: "hidden",
    },
    projectCardBackgroundImage: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      position: "absolute",
      top: 0,
      left: 0,
      zIndex: 0,
    },
    projectCardBackgroundOverlay: {
      display: "flex",
      flex: 1,
      flexDirection: "column",
      zIndex: 1,
      width: "100%",
      boxSizing: "border-box",
      padding: isSmallScreen ? 16 : 26,
      minHeight: 0,
    },
    projectCardImageContainer: {
      marginBottom: 10,
      width: "100%",
      minHeight: "150px",
      maxHeight: "151px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderRadius: 10,
      zIndex: 1,
      position: "relative",
      backgroundColor: theme[themeName].projectCardImageContainer,
    },
    projectCardImage: {
      width: "100%",
      height: "100%",
      objectFit: "contain",
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 1,
    },
    projectCardRowContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      gap: "1%",
    },
    projectCardColumnContainer: {
      display: "flex",
      flexDirection: "column",
      width: "100%",
    },
  };
};

export default useStyles;
