import theme from "../theme";

const useStyles = ({ themeName, isSmallScreen }) => {
  return {
    mainContainer: {
      width: "100vw",
      height: "100vh",
      boxSizing: "border-box",
      backgroundColor: theme[themeName].background,
    },
    mainInnerContainer: {
      width: "100%",
      height: "100%",
      zIndex: 5,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
    },
    mainInnerBodyContainer: {
      width: "100%",
      height: "100%",
      overflowY: "scroll",
      zIndex: 5,
    },
    backgroundImg: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      position: "absolute",
      top: 0,
      left: 0,
      zIndex: 1,
    },
    headerMainContainer: {
      width: "100%",
      height: isSmallScreen ? "60px" : "70px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme[themeName].headerBack,
      paddingLeft: "5%",
      paddingRight: "5%",
      boxSizing: "border-box",
      zIndex: 10,
      boxShadow: theme[themeName].headerShadow,
    },
    headerTitle: {
      color: theme[themeName].headerText,
      fontSize: isSmallScreen ? "28px" : "32px",
      fontWeight: "bold",
      fontFamily: theme[themeName].font_saira,
    },
    headerIconContainer: {
      display: "flex",
      gap: "10px",
    },
    headerMenuIconContainer: {
      height: theme[themeName].headerIconSize,
      width: theme[themeName].headerIconSize,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    headerMenuIcon: {
      color: theme[themeName].headerIcon,
    },
    modalMainContainer: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      backgroundColor: theme[themeName].menuModalBack,
      display: "flex",
      justifyContent: "flex-end",
      zIndex: 1000,
    },
    menuContainer: {
      width: "250px",
      height: "100%",
      backgroundColor: theme[themeName].headerBack,
      padding: "20px",
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    menuElement: {
      padding: isSmallScreen ? "5px" : "10px",
      cursor: "pointer",
      fontSize: isSmallScreen ? "12px" : "16px",
      fontFamily: theme[themeName].font_poppins,
      color: theme[themeName].headerText,
      borderBottom: `1px solid ${theme[themeName].menuBorder}`,
      justifyContent: "space-between",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
    },
    sectionContainerTransparent: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      paddingLeft: "5%",
      paddingRight: "5%",
      boxSizing: "border-box",
      paddingTop: "5%",
      paddingBottom: "7%",
      backgroundColor: theme[themeName].sectionBackgroundTransparent,
      borderBottom: "2px solid #000",
    },
    sectionContainerSolid: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      paddingLeft: "5%",
      paddingRight: "5%",
      boxSizing: "border-box",
      paddingTop: "5%",
      paddingBottom: "7%",
      backgroundColor: theme[themeName].sectionBackgroundSolid,
      borderBottomWidth: "2px solid #000",
    },
    //----------------------------------------------------
    sectionTitleTransparent: {
      width: "100%",
      fontSize: isSmallScreen ? "28px" : "32px",
      fontWeight: "bold",
      color: theme[themeName].sectionHeaderTransparent,
      fontFamily: theme[themeName].font_saira,
      borderBottom: `2px solid ${theme[themeName].sectionHeaderBorderTransparent}`,
    },
    sectionBodyTransparent: {
      width: "100%",
      paddingTop: "10px",
      paddingBottom: "10px",
    },
    sectionPoppinsBoldTextTransparent: {
      color: theme[themeName].sectionPoppinsBoldTextTransparent,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? "12px" : "16px",
      fontWeight: "bold",
      marginTop: isSmallScreen ? "5px" : "10px",
    },
    sectionPoppinsRegularTextTransparent: {
      color: theme[themeName].sectionPoppinsRegularTextTransparent,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? "12px" : "16px",
    },
    sectionTitleSolid: {
      width: "100%",
      fontSize: isSmallScreen ? "28px" : "32px",
      fontWeight: "bold",
      color: theme[themeName].sectionHeaderSolid,
      fontFamily: theme[themeName].font_saira,
      borderBottom: `2px solid ${theme[themeName].sectionHeaderBorderSolid}`,
    },
    sectionBodySolid: {
      width: "100%",
      paddingTop: "10px",
      paddingBottom: "10px",
    },
    sectionPoppinsBoldTextSolid: {
      color: theme[themeName].sectionPoppinsBoldTextSolid,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? "12px" : "16px",
      fontWeight: "bold",
      marginTop: isSmallScreen ? "5px" : "10px",
      width: "100%",
    },
    sectionPoppinsRegularTextSolid: {
      color: theme[themeName].sectionPoppinsRegularTextSolid,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? "12px" : "16px",
      width: "100%",
    },
    introMainContainer: {
      flex: 1,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    introLeftContainer: {
      width: "50%",
      justifyContent: "center",
      alignItems: "center",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      position: "relative",
      borderRadius: "20px",
    },
    introRightContainer: {
      width: "50%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      height: "100%",
      paddingLeft: "5%",
      boxSizing: "border-box",
    },
    introImg: {
      width: "85%",
      height: "85%",
      objectFit: "cover",
    },
    introImgOverlay: {
      width: "100%",
      height: "30%",
      background: theme[themeName].introImgOverlay,
      position: "absolute",
      bottom: 0,
      zIndex: -1,
    },
    buttonStyle: {
      textTransform: "capitalize",
      width: 150,
      backgroundColor: theme[themeName].buttonColor,
      color: theme[themeName].buttonText,
      fontSize: isSmallScreen ? "12px" : "16px",
      fontFamily: theme[themeName].buttonFont,
      borderRadius: "7px",
    },
    introSubtitle: {
      textTransform: "capitalize",
      color: theme[themeName].introSubtitle,
      fontSize: "clamp(16px, 2vw, 24px)",
      fontFamily: theme[themeName].font_poppins,
    },
    introTitle: {
      textTransform: "capitalize",
      color: theme[themeName].introTitle,
      fontFamily: theme[themeName].font_saira,
      fontWeight: "bold",
      fontSize: "clamp(32px, 4vw, 72px)",
    },
    introDesc: {
      textTransform: "capitalize",
      color: theme[themeName].introDesc,
      fontSize: "clamp(16px, 2vw, 24px)",
      fontFamily: theme[themeName].font_poppins,
      marginBottom: 20,
    },
    aboutDesc: {
      width: "100%",
      paddingTop: "10px",
      paddingBottom: "10px",
      fontSize: isSmallScreen ? "12px" : "16px",
      color: theme[themeName].aboutText,
      fontFamily: theme[themeName].font_poppins,
      textTransform: "capitalize",
    },
    qualificationText: {
      width: "100%",
      paddingTop: "10px",
      paddingBottom: "10px",
      fontSize: isSmallScreen ? "12px" : "16px",
      color: theme[themeName].aboutText,
      fontFamily: theme[themeName].font_poppins,
      textTransform: "capitalize",
    },
    serviceCard: {
      padding: "5px 20px",
      borderRadius: "5px",
      backgroundColor: theme[themeName].serviceCard,
      boxSizing: "border-box",
      boxShadow: `${isSmallScreen ? "5px" : "7px"} ${isSmallScreen ? "5px" : "7px"} ${isSmallScreen ? "5px" : "7px"} ${theme[themeName].serviceCard}80`,
      color: theme[themeName].serviceCardText,
      fontFamily: theme[themeName].font_poppins,
      fontSize: isSmallScreen ? "12px" : "16px",
    },
    projectContainer: {
      width: "100%",
      overflowX: "scroll",
      display: "flex",
      flexDirection: "row",
      gap: "20px",
      padding: "20px 0px",
      boxSizing: "border-box",
    },
    projectCard: {
      width: "400px",
      height: "510px",
      flexShrink: 0,
      background: theme[themeName].projectCard,
      borderRadius: "10px",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      boxShadow: `isSmallScreen ? "5px" : "7px" isSmallScreen ? "5px" : "7px" isSmallScreen ? "5px" : "7px" ${theme[themeName].projectCard}33`,
      position: "relative",
      flexDirection: "column",
      overflow: "hidden",
    },
    projectCardBackgroundImage: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      position: "absolute",
      top: 0,
      left: 0,
      zIndex: 0,
    },
    projectCardBackgroundOverlay: {
      display: "flex",
      flex: 1,
      flexDirection: "column",
      zIndex: 1,
      width: "100%",
      boxSizing: "border-box",
      padding: isSmallScreen ? "16px" : "26px",
      minHeight: 0,
    },
    projectCardImageContainer: {
      marginBottom: "10px",
      width: "100%",
      minHeight: "150px",
      maxHeight: "151px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderRadius: "10px",
      zIndex: 1,
      position: "relative",
      backgroundColor: theme[themeName].projectCardImageContainer,
    },
    projectCardImage: {
      width: "100%",
      height: "100%",
      objectFit: "contain",
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 1,
    },
    projectCardRowContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      gap: "1%",
    },
    projectCardColumnContainer: {
      display: "flex",
      flexDirection: "column",
      width: "100%",
    },
  };
};

export default useStyles;
